// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS392_WebApplication.Migrations.ProductsDb
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260411230817_AddGoogleProductId")]
    partial class AddGoogleProductId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS392_WebApplication.Models.Product_list", b =>
                {
                    b.Property<int>("listID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("listID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("listID"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("grade_level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("grade_level");

                    b.Property<bool>("is_published")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<int>("list_type")
                        .HasColumnType("int")
                        .HasColumnName("list_type");

                    b.Property<string>("title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<double>("total_price")
                        .HasColumnType("float")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("userID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("listID");

                    b.ToTable("Product_list");
                });

            modelBuilder.Entity("CS392_WebApplication.Models.Product_list_items", b =>
                {
                    b.Property<int>("list_items_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("list_itemsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("list_items_ID"));

                    b.Property<bool>("is_required")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<int>("list_ID")
                        .HasColumnType("int")
                        .HasColumnName("listID");

                    b.Property<float>("price_at_purchase")
                        .HasColumnType("real")
                        .HasColumnName("price_at_purchase");

                    b.Property<int>("product_ID")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<int>("purchase_type")
                        .HasColumnType("int")
                        .HasColumnName("purchase_type");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("recommended_quantity")
                        .HasColumnType("int")
                        .HasColumnName("recommended_quantity");

                    b.Property<string>("teacher_note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher_note");

                    b.HasKey("list_items_ID");

                    b.ToTable("Product_list_items");
                });

            modelBuilder.Entity("CS392_WebApplication.Models.Products", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("bulk_availability")
                        .HasColumnType("bit")
                        .HasColumnName("bulk_availability");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("google_product_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("google_product_id");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.Property<double?>("rating")
                        .HasColumnType("float")
                        .HasColumnName("item_rating");

                    b.Property<string>("retail_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("retail_URL");

                    b.Property<double>("retail_price")
                        .HasColumnType("float")
                        .HasColumnName("retail_price");

                    b.Property<int?>("reviews")
                        .HasColumnType("int")
                        .HasColumnName("item_reviews");

                    b.Property<string>("sample_review")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sample_review");

                    b.Property<string>("source_logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_logo");

                    b.Property<string>("source_name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("source_name");

                    b.HasKey("product_ID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
