// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS392_WebApplication.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS392_WebApplication.Models.Product_list", b =>
                {
                    b.Property<int>("listID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("listID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("listID"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("list_type")
                        .HasColumnType("int")
                        .HasColumnName("list_type");

                    b.Property<double>("total_price")
                        .HasColumnType("float")
                        .HasColumnName("total_price");

                    b.Property<int>("userID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("listID");

                    b.ToTable("Product_list");
                });

            modelBuilder.Entity("CS392_WebApplication.Models.Products", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("bulk_availability")
                        .HasColumnType("bit")
                        .HasColumnName("bulk_availability");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.Property<float?>("rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<string>("retail_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("retail_URL");

                    b.Property<double>("retail_price")
                        .HasColumnType("float")
                        .HasColumnName("retail_price");

                    b.Property<int?>("reviews")
                        .HasColumnType("int")
                        .HasColumnName("reviews");

                    b.Property<string>("sample_Review")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sample Review");

                    b.Property<string>("source_logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_logo");

                    b.Property<string>("source_name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("source_name");

                    b.HasKey("product_ID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
