// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS392_WebApplication.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS392_WebApplication.Models.Product_list", b =>
                {
                    b.Property<int>("list_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("list_ID"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("list_type")
                        .HasColumnType("int");

                    b.Property<float>("total_price")
                        .HasColumnType("real");

                    b.Property<int>("user_ID")
                        .HasColumnType("int");

                    b.HasKey("list_ID");

                    b.ToTable("Product_list");
                });

            modelBuilder.Entity("CS392_WebApplication.Models.Product_list_items", b =>
                {
                    b.Property<int>("list_items_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("list_items_ID"));

                    b.Property<int>("list_ID")
                        .HasColumnType("int");

                    b.Property<float>("price_at_purchase")
                        .HasColumnType("real");

                    b.Property<int>("product_ID")
                        .HasColumnType("int");

                    b.Property<int>("purchase_type")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("list_items_ID");

                    b.ToTable("Product_list_items");
                });

            modelBuilder.Entity("CS392_WebApplication.Models.Products", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<bool>("bulk_availability")
                        .HasColumnType("bit")
                        .HasColumnName("bulk_availability");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.Property<string>("retail_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("retail_URL");

                    b.Property<double>("retail_price")
                        .HasColumnType("float")
                        .HasColumnName("retail_price");

                    b.HasKey("product_ID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
